### ISSUE TITLE
Firebase Storage dependencie

### ISSUE THREAD

**Issue by benitogonzalezh** [oxequa/flutter_cache_image#12]
I am using Firebase Storage 4.0.0 in my project and this package have a problem with that version.

I made a fork with the change for an appropiate usage and also I made a pull request with the change,

``` yaml
  cache_image:
    git:
      url: https://github.com/benitogonzalezh/flutter_cache_image
```
